apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: vote
  name: vote
  namespace: stginstavote
spec: 
  replicas: 3
  spec: 
    containers: 
    - image: schoolofdevops/vote:v5
      name: vote