apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
  namespace: stginstavote
spec: 
  replicas: 4
  spec: 
    containers: 
    - image: schoolofdevops/vote:v3
      name: vote