apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
  namespace: stginstavote
spec:
  ports:
  - name: "80"
    nodePort: 30001
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: vote
  type: NodePort
